config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/book", to: "static_pages#user_booking"
    devise_for :users, skip: :omniauth_callbacks, controllers: {registrations: "users"}
    resources :users do
      member do
        get "/book", to: "users#show_bookings"
        get "/payment", to: "users#show_payments"
      end
    end
    resources :rooms, only: %i(index show)
    resources :room_types, only: :show
    resources :bookings do
      get "delete"
    end
    resources :payments, only: %i(new create show)
  end
end

app/views/layouts/user_layouts/_footer.html.erb
<footer class="tm-footer">
  <div class="tm-us">
    <p class="bold"><%= t ".about_us" %></p>
    <p>
      <%= t ".about_descrip" %>
    </p>
  </div>
  <div class="tm-address">
    <p class="bold"><%= t ".address" %></p>
    <p>
      <%= t ".address_" %>
    </p>
  </div>
</footer>

app/views/layouts/user_layouts/_header.html.erb
<header class="header_area">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <!-- Brand and toggle get grouped for better mobile display -->
      <%= link_to home_path, class:"navbar-brand logo_h" do %>
        <%= image_tag Settings.src.logo, :alt => "Logo" %>
      <% end %>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
        <ul class="nav navbar-nav menu_nav ml-auto">
          <% if current_user&.admin? || current_user&.staff? %>
            <li class="nav-item">
              <%= link_to t(".admin"), rails_admin.dashboard_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t(".home"), home_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to t(".booking"), book_path, class: "nav-link" %>
          </li>
          <li class="nav-item submenu dropdown">
            <%= link_to "#", class:"nav-link dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t ".review" %>
            <% end %>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <%= link_to t(".staffs"), "#", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to t(".rooms"), "#", class: "nav-link" %>
              </li>
            </ul>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item submenu dropdown">
              <%= link_to "#", class:"nav-link dropdown-toggle", "data-toggle": "dropdown" do %>
                <%= current_user.name %>
              <% end %>
              <ul class="dropdown-menu">
                <li class="nav-item">
                  <%= link_to t(".profile"), current_user, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to t(".show_bookings"), book_user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to t(".show_payments"), payment_user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to t(".setting"), edit_user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to t(".logout"), destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t(".login"), new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to t(".contact"), help_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
      <ul class="nav navbar-nav menu_nav">
       <li class="nav-item">
          <div class="nav-link flag">
            <%= link_to image_tag("en.png", alt: "Logo"), locale:"en" %>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-link flag">
            <%= link_to image_tag("vi.png", alt: "Logo"), locale:"vi" %>
          </div>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/user_layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "i18n" %>
    <%= javascript_include_tag "translations", skip_pipeline: true %>
  </head>

  <body>
    <%= render "layouts/user_layouts/header" %>
    <div class="content-area">
      <%= content_tag(:script) do %>
        <% flash.each do |type, message| %>
          <%= toastr_flash_class("#{type}") %>('<%= message %>')
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/user_layouts/footer" %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale || I18n.default_locale %>";
    </script>
  </body>
</html>