config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/book", to: "static_pages#user_booking"
    devise_for :users, skip: :omniauth_callbacks, controllers: {registrations: "users"}
    resources :users do
      member do
        get "/book", to: "users#show_bookings"
        get "/payment", to: "users#show_payments"
      end
    end
    resources :rooms, only: %i(index show)
    resources :room_types, only: :show
    resources :bookings do
      get "delete"
    end
    resources :payments, only: %i(new create show)
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user

  delegate :room_number, to: :room
  delegate :duration, to: :class

  attr_accessor :room_type, :total

  PERMITTED = %i(room_id user_id checkin checkout).freeze

  after_destroy :update_room_status

  validates :checkin, presence: true, date: {after: Time.zone.today}
  validates :checkout, presence: true, date: {after: :checkin}

  scope :non_checkout, ->{where is_checkout: false}
  scope :recent, ->{order created_at: :desc}
  scope :count_by_room_type, (lambda do
    joins(room: :room_type)
      .where(
        "bookings.created_at >= ?",
        Time.zone.now - Settings.statistic.default.month_ago.months
      )
      .group(:room_type_id)
      .count
  end)

  class << self
    def create_bookings params, room_ids, user_id
      Booking.transaction do
        room_ids.each do |room_id|
          booking = Booking.new booking_params(params, room_id, user_id)
          booking.save!
          Room.transaction do
            booking.room.update! is_available: false
            raise ActiveRecord::Rollback
          end
        end
      end
    rescue ActiveRecord::RecordInvalid
      false
    end

    def booking_params params, room_id, user_id
      params[:booking].merge! room_id: room_id, user_id: user_id
      params.require(:booking).permit PERMITTED
    end
  end

  def duration
    [checkin.to_date, checkout.to_date].join(" -> ")
  end

  private

  def update_room_status
    room.update! is_available: true
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include BookingsHelper

  before_action :authenticate_user!
  before_action :check_numberic, :booked_room_ids, only: :create
  before_action :load_booking, except: :create
  before_action :check_change_booking, only: %i(update destroy)

  def show; end

  def create
    if Booking.create_bookings params, @booked_room_ids, current_user.id
      flash[:success] = t ".success"
      redirect_to book_user_path(current_user)
    else
      flash[:danger] = t ".fail"
      redirect_to book_path(booking: book_data)
    end
  end

  def edit; end

  def update
    if @booking.update booking_params
      flash[:success] = t ".booking_updated"
      redirect_to current_user
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  def delete; end

  def destroy
    @booking.destroy!

    flash[:success] = t ".booking_deleted"
    redirect_to current_user
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t ".delete_fail"
    redirect_to current_user
  end

  private

  def booking_params
    params.require(:booking).permit Booking::PERMITTED
  end

  def check_numberic
    @total = params.dig(:booking, :total).to_i
    return unless @total < 1

    flash[:danger] = t ".fail"
    redirect_to book_path
  end

  def booked_room_ids
    @booked_room_ids = Room.available
                           .by_room_type_id(params[:booking][:room_type])
                           .limit(@total)
                           .ids
    return if @booked_room_ids.present?

    flash[:danger] = t ".fail"
    redirect_to book_path
  end

  def check_change_booking
    return unless is_deadline_expired? @booking.created_at

    flash[:danger] = t ".errors.deadline_expired"
    redirect_to current_user
  end

  def load_booking
    id = params[:id].presence || params[:booking_id]
    @booking = Booking.find_by id: id
    return if @booking

    flash[:danger] = t ".errors.not_found"
    redirect_to current_user
  end

  def book_data
    params[:booking].permit(:checkin, :checkout).to_enum.to_h
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def total_calculate booking
    start_date = booking.checkin.to_date
    end_date = booking.checkout.to_date
    (start_date..end_date).count * booking.room.room_type.cost
  end

  def checkout_to_text is_checkout
    is_checkout ? t(".checkout") : t(".non_checkout")
  end

  def is_deadline_expired? start_date
    due_date = start_date + Settings.due_time.minutes
    due_date.before? Time.zone.now
  end
end

app/views/bookings/_booking.html.erb
<tr id="booking-<%= booking.id %>">
  <td><%= link_to booking.room_number, booking.room,
        {remote: true, "data-toggle": "modal", "data-target": "#room-modal"} %>
  </td>
  <div id="room-modal" class="modal fade" role="dialog"></div>
  <td><%= booking.room.room_type.name %></td>
  <td><%= booking.updated_at.to_date %></td>
  <td><%= booking.checkin.to_date %></td>
  <td><%= booking.checkout.to_date %></td>
  <td><%= total_calculate booking %> <%= t "currency" %></td>
  <td>
    <button type="button" class="btn status-btn <%= status_btn_color booking.is_checkout %>">
      <%= checkout_to_text booking.is_checkout %>
    </button>
  </td>
  <% if is_deadline_expired?(booking.created_at) || booking.is_checkout %>
    <td colspan="2"></td>
  <% else %>
    <td>
      <%= link_to edit_booking_path(booking), remote: true, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    </td>
    <td>
      <%= link_to booking_delete_path(booking), remote: true, class: "btn btn-danger" do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/bookings/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4><%= t ".header" %> <%= @booking.room.room_number %></h4>
    </div>
    <div class="modal-body">
      <p><%= t ".body" %><b><%= t ".room" %> <%= @booking.room.room_number %></b><%= t ".symbol" %></p>
    </div>
    <div class="modal-footer">
      <%= link_to t(".yes_ans"), booking_path(@booking), method: :delete, remote: true, class: "btn btn-danger" %>
      <%= link_to t(".no_ans"), "#", class: "btn btn-default", data: { dismiss: "modal" } %>
    </div>
  </div>
</div>

app/views/bookings/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4><%= t ".header" %> <%= @booking.room.room_number %></h4>
    </div>
    <%= form_for @booking, remote: true do |f| %>
      <div class="modal-body">
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label :checkin, class:"control-label" %>
          <div class="input-group date">
            <%= f.date_field :checkin, class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :checkout, class: "control-label" %>
          <div class="input-group date" id="datetimepicker">
            <%= f.date_field :checkout, class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit t(".submit"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/delete.js.erb
$('#booking-modal').html('<%= j render "delete" %>')
$('#booking-modal').modal('show')

app/views/bookings/edit.js.erb
$('#booking-modal').html('<%= j render "edit" %>')
$('#booking-modal').modal('show')