config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/book", to: "static_pages#user_booking"
    devise_for :users, skip: :omniauth_callbacks, controllers: {registrations: "users"}
    resources :users do
      member do
        get "/book", to: "users#show_bookings"
        get "/payment", to: "users#show_payments"
      end
    end
    resources :rooms, only: %i(index show)
    resources :room_types, only: :show
    resources :bookings do
      get "delete"
    end
    resources :payments, only: %i(new create show)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  attr_accessor :remember_token

  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save :downcase_email

  has_many :bookings, dependent: :destroy
  has_many :rooms, through: :bookings
  has_many :reviews, as: :commentable, dependent: :destroy
  has_many :payments, dependent: :destroy

  enum gender: {female: 0, male: 1}
  enum role: {customer: -1, staff: 0, admin: 1}
  PERMITTED = %i(name email gender phone password password_confirmation).freeze
  PERMITTED2 = %i(name email gender phone password
                  password_confirmation role).freeze

  validates :name, presence: true,
                   length: {maximum: Settings.validation.name.length.max}
  validates :email, presence: true,
            length: {maximum: Settings.validation.email.length.max},
            format: {with: Settings.validation.email.valid_regex},
            uniqueness: {case_sensitive: false}
  validates :password, presence: true,
            length: {minimum: Settings.validation.password.length.min},
            allow_nil: true
  validates :phone, length: {is: Settings.validation.phone.length},
            allow_nil: true

  scope :customer, ->{where(role: :customer)}
  scope :new_user, (lambda do |month_ago|
    where("created_at >= ?", Time.zone.now - month_ago.months)
  end)
  scope :new_user_by_month, (lambda do
    group_by_month(
      :created_at,
      last: Settings.statistic.default.month_ago,
      format: "%b %Y"
    ).count
  end)

  def self.from_omniauth auth
    result = User.find_by email: auth.info.email
    return result if result

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.uid = auth.uid
      user.provider = auth.provider
      user.activated = true
    end
  end

  private
  def downcase_email
    email.downcase!
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    generic_callback("facebook")
  end

  def google_oauth2
    generic_callback("google_oauth2")
  end

  def generic_callback provider
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: provider.capitalize)
      end
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
                                                  .except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :load_user, except: %i(new create)
  before_action :load_user, except: %i(new create)

  def new
    @user = User.new
  end

  def show; end

  def show_bookings
    @q_booking = @user.bookings.joins(room: :room_type).ransack(params[:q])
    @all_bookings = @q_booking.result
    @all_bookings = @all_bookings.order(params[:q][:s]) if params[:q]
    @bookings = @all_bookings.page(params[:page]).per(5)
  end

  def show_payments
    @q_payment = @user.payments.ransack(params[:q])
    @all_payments = @q_payment.result
    @all_payments = @all_payments.order(params[:q][:s]) if params[:q]
    @payments = @all_payments.page(params[:page]).per(5)
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t ".success"
      redirect_to new_user_session_path
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = t ".success"
      redirect_to @user
    else
      flash[:danger] = t ".fail"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit User::PERMITTED
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def select_gender
    User.genders.map{|s| [t(".#{s[0]}"), s[0]]}
  end

  def show_gender gender
    return "nil" if gender.nil?

    gender.to_s
  end

  def select_default_ava user
    user.male? ? Settings.default_ava.male : Settings.default_ava.female
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :gender %>
  <%= f.select :gender, select_gender, prompt: t(".select"),
                              class: "form-control" %>
  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation%>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit t(".submit"), class: "btn btn-primary mt-30" %>
<% end %>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<%= render "shared/breadcrumb" %>
<div class="container content-padding">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<%= render "shared/breadcrumb" %>
<div class="container content-padding">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @user, url: users_path do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
        <%= f.label :gender %>
        <%= f.select :gender, select_gender, prompt: t(".select"),
                              class: "form-control" %>
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation, class: "form-control" %>
        <%= f.submit t(".submit"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, t(".profile") %>
<%= render "shared/breadcrumb" %>
  <section class="user_info">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="default_image">
          <%= image_tag select_default_ava(@user), :class => "style_image" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <h2><%= @user.name %></h2>
        <p><strong><%= t ".email" %></strong><%= @user.email %></p>
        <p><strong><%= t ".gender" %></strong><%= t "users.form.#{show_gender @user.gender}" %></p>
        <p><strong><%= t ".phone" %></strong><%= @user.phone %></p>
      </div>
    </div>
  </section>
</div>

app/views/users/show_bookings.html.erb
<% provide :title, t(".bookings_title") %>
<%= render "shared/breadcrumb" %>
  <section class="booking_list_area section_gap">
    <div class="container">
      <div class="section_title text-center">
        <p><%= t ".bookings_subtitle" %></p>
        <div class="checkout-btn"><%= link_to t(".checkout"), new_payment_path, class: "view_btn button_hover" %></div>
      </div>
      <div class="card shadow">
        <div class="table-responsive">
          <table id="mytable" class="table table-bordred table-striped">
            <thead>
              <th><%= sort_link @q_booking, :room_number, t(".room_number") %></th>
              <th><%= sort_link @q_booking, :name, t(".room_type") %></th>
              <th><%= sort_link @q_booking, :created_at, t(".booking_date") %></th>
              <th><%= sort_link @q_booking, :checkin, t(".checkin") %></th>
              <th><%= sort_link @q_booking, :checkout, t(".checkout") %></th>
              <th><%= t ".total" %></th>
              <th><%= sort_link @q_booking, :is_checkout, t(".is_checkout") %></th>
              <th><%= t ".edit" %></th>
              <th><%= t ".cancel" %></th>
            </thead>
            <tbody>
              <% if @bookings.any? %>
                <%= render @bookings %>
              <% else %>
                <p class="text-center no-record"><%= t ".no_booking" %></p>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= paginate @bookings %>
      </div>
    </div>
    <div id="booking-modal" class="modal fade"></div>
  </section>
</div>

app/views/users/show_payments.html.erb
<% provide :title, t(".bills_title") %>
<%= render "shared/breadcrumb" %>
  <section class="bills_list_area section_gap">
    <div class="container">
      <div class="section_title text-center">
        <p><%= t ".bills_subtitle" %></p>
      </div>
      <div class="card shadow">
        <div class="table-responsive">
          <table id="mytable" class="table table-bordred table-striped">
            <thead>
              <th><%= sort_link @q_payment, :id, t(".bill_id") %></th>
              <th><%= sort_link @q_payment, :created_at, t(".created_date") %></th>
              <th><%= sort_link @q_payment, :amount, t(".total") %></th>
              <th><%= sort_link @q_payment, :is_paid, t(".is_paid") %></th>
            </thead>
            <tbody>
              <% if @payments.any? %>
                <%= render @payments %>
              <% else %>
                <p class="text-center no-record"><%= t ".no_payment" %></p>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= paginate @payments %>
      </div>
    </div>
  </section>
</div>