config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/book", to: "static_pages#user_booking"
    devise_for :users, skip: :omniauth_callbacks, controllers: {registrations: "users"}
    resources :users do
      member do
        get "/book", to: "users#show_bookings"
        get "/payment", to: "users#show_payments"
      end
    end
    resources :rooms, only: %i(index show)
    resources :room_types, only: :show
    resources :bookings do
      get "delete"
    end
    resources :payments, only: %i(new create show)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, as: :commentable, dependent: :destroy
  belongs_to :room_type

  extend FriendlyId
  friendly_id :room_number, use: :slugged

  ROOM_PERMITTED = %i(room_number description room_type_id).freeze

  validates :room_number, presence: true
  validates :description, presence: true,
                  length: {maximum: Settings.validation.description.length.max}

  scope :available, ->{where(is_available: true)}
  scope :not_available, ->{where(is_available: false)}
  scope :by_room_type_id, ->(room_type){where(room_type_id: room_type)}

  rails_admin do
    create do
      exclude_fields :bookings, :users, :reviews
    end
    edit do
      exclude_fields :bookings, :users, :reviews
    end
  end

  def normalize_friendly_id text
    ["room", text].join("-")
  end
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  has_many :rooms, dependent: :destroy
  accepts_nested_attributes_for :rooms, allow_destroy: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many_attached :images
  ROOMTYPE_PERMITTED = %i(name cost bed_num air_conditioner description).freeze

  validates :name, presence: true
  validates :description, presence: true,
                  length: {maximum: Settings.validation.description.length.max}
  validates :bed_num, :cost, presence: true,
                  numericality: {greater_than: Settings.validation.item.min}
  validates :images,
            content_type: {
              in: Settings.validation.image.type,
              message: :invalid_format
            },
            size: {
              less_than: Settings.validation.image.max_size.megabytes,
              message: :required_size
            }

  scope :most_available, (lambda do
    joins(:rooms)
      .select("room_types.*, count(rooms.id) as available_number")
      .where("rooms.is_available = true")
      .group(:id)
      .order(available_number: :desc)
  end)

  def normalize_friendly_id text
    room_type_code = text.split(" ").last[1..-2]
    ["room", "type", room_type_code].join("-")
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = if params[:room_type].present?
               RoomType.find_by(id: params[:room_type]).rooms.available
             else
               Room.available
             end

    return unless request.xhr?

    respond_to do |format|
      format.json{render json: {rooms: @rooms}}
    end
  end

  def show
    @room = Room.find_by slug: params[:id]
    if @room
      @room_type = RoomType.find_by id: @room.room_type_id
    else
      flash[:warning] = t ".not_found"
      redirect_to root_path
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def select_room_type
    RoomType.pluck :description, :id
  end

  def show_room room
    t("rooms.show.title") + room.room_number
  end
end

app/views/rooms/_show.html.erb
<div class="modal-dialog modal-xl">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel">
        <%= t ".room" %> <%= @room.room_number %>
         - <%= @room_type.name %>
      </h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-7">
          <div class="pro-img-details">
            <%= image_tag @room_type.images.first %> <br />
          </div>
          <div class="pro-img-list">
            <% @room_type.images[1..3].each do |image| %>
              <%= image_tag image %> <br />
            <% end %>
          </div>
        </div>
        <div class="info col-md-5">
          <div class="rt-info">
            <strong><%= t ".room" %> <%= @room_type.name%></strong>
            <p><%= @room_type.description %></p>
            <hr>
            <div class="row">
              <strong class="col-md-6"><%= t ".bed" %></strong>
              <div class="number col-md-6"><%= @room_type.bed_num %></div>
            </div>
            <div class="row">
              <strong class="col-md-6"><%= t ".air_conditioner" %></strong>
              <div class="number col-md-6"><%= boolean_to_text @room_type.air_conditioner %></div>
            </div>
            <hr>
            <div class="row">
              <strong class="col-md-6"><%= t ".cost" %></strong>
              <strong class="number col-md-6"><%= @room_type.cost %><%= t ".per_day" %></strong>
            </div>
          </div>
          <div class="room-info">
            <h4><%= t ".description" %></h4>
            <p><%= @room.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<% provide :title, t(".title") %>
<%= render "shared/breadcrumb" %>
<div class="container content-padding">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @room, url: rooms_path do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label :room_number %>
        <%= f.text_field :room_number, class: "form-control" %>
        <%= f.label :room_type_id %>
        <%= f.select :room_type_id, select_room_type, prompt: t(".select"), class: "form-control" %>
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
        <%= f.label :images %>
        <%= f.file_field :images, multiple: true %><br>
        <%= f.submit t(".submit"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.js.erb
$('#room-modal').html('<%= j render "show" %>')
$('#room-modal').modal('show')